import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Navbar from "./_components/navbar"; // Navbar'ı import edin

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Mini Campaign App",
  description: "Generated by ThePrelior",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider><Navbar />{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
