import "~/styles/globals.css";

import { type Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import Navbar from "./_components/navbar"; // Navbar import

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Mini Campaign App",
  description: "Generated by ThePrelior",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
   <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
  <body>
    <TRPCReactProvider>
      <Navbar /> {/*Added navbar */}
      {children}
    </TRPCReactProvider>
  </body>
</html>

  );
}
